# Generated by Django 3.2.8 on 2021-10-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
